// Tarea S4.1 del roadmap: añade el nivel CEFR (A1-C1) de cada phrasal verb.
//
// NOTA IMPORTANTE: el dataset previsto (Talhakasikci/cefr-vocabulary-dataset) resultó ser
// vocabulario general de una sola palabra: de los 155 verbos únicos del curso, CERO aparecen
// como entrada (comprobado exhaustivamente contra las 5 listas en/es-A1..C1). Un cruce
// automático habría dado 0/155 coincidencias, así que el mapeo de abajo está curado a mano
// por frecuencia/idiomaticidad general en ELT (no verificado contra el temario real de
// Conquer English, que no está en este repositorio) — decisión tomada con el usuario.

import fs from 'node:fs';
import path from 'node:path';

const DATA_FILE = path.resolve('phrasal_verbs_data.json');

const CEFR_MAP = {
  'go up': 'A2',
  'pick up': 'A2',
  'climb up': 'A2',
  'blow up': 'B1',
  'fill up': 'A2',
  'speak up': 'B1',
  'speed up': 'B1',
  'turn up': 'B1',
  'break up': 'B1',
  'end up': 'B1',
  'give up': 'A2',
  'hang up': 'A2',
  'use up': 'B1',
  'wake up': 'A1',
  'wait up': 'B2',
  'stay up': 'B1',
  'get up': 'A1',
  'catch up': 'B1',
  'catch up (with/to)': 'B1',
  'come up': 'A2',
  'go up to': 'A2',
  'make up': 'B1',
  'draw up': 'B2',
  'come up with': 'B1',
  'take up': 'B1',
  'set up': 'A2',
  'start up': 'B1',
  'sign up': 'A2',
  'back up': 'B1',
  'dress up': 'A2',
  'look up': 'A2',
  'go down': 'A1',
  'put down': 'A2',
  'sit down': 'A1',
  'lie down': 'A1',
  'slow down': 'A2',
  'calm down': 'A2',
  'turn down': 'B1',
  'copy down': 'A2',
  'note down': 'A2',
  'write down': 'A1',
  'break down': 'B1',
  'let down': 'B1',
  'shut down': 'B1',
  'come in': 'A1',
  'coming and going: a visit to the doctor': 'A2',
  'get in': 'A2',
  'get into': 'B1',
  'run in': 'B1',
  'run around': 'B1',
  'walk in': 'A2',
  'break in': 'B1',
  'take in': 'B2',
  'sink in': 'B2',
  'fill in': 'A2',
  'fill in for': 'B1',
  'stand in': 'B1',
  'stand in for': 'B1',
  'hand in': 'A2',
  'fill in, hand in': 'A2',
  'send in': 'B1',
  'pop in': 'B1',
  'drop in': 'B1',
  'drop in on': 'B1',
  'put in': 'A2',
  'stuff in': 'B2',
  'plug in': 'A2',
  'push in': 'B1',
  'butt in': 'B2',
  'bump into': 'B1',
  'turn into': 'B1',
  'look into': 'B1',
  'move in': 'A2',
  'move in / move out': 'A2',
  'bring in': 'B1',
  'fill in / fill out': 'A2',
  'check in': 'A2',
  'check in (aeropuerto / equipaje)': 'A2',
  'hand out': 'B1',
  'give out': 'B1',
  'send out': 'B1',
  'come out / go out': 'A2',
  'get out': 'A2',
  'get out of, figure out': 'B1',
  'run out / to rush out': 'B1',
  'walk out': 'B1',
  'go out': 'A1',
  'put out': 'A2',
  'bring out': 'B1',
  'come out': 'A2',
  'back out': 'B2',
  'drop out': 'B1',
  'pull out': 'B1',
  'count out': 'B2',
  'count out / count in': 'B2',
  'rule out': 'B2',
  'kick out': 'B1',
  'drive out': 'B2',
  'iron out': 'C1',
  'sort out': 'B1',
  'figure out': 'B1',
  'take out': 'A2',
  'find out': 'A2',
  'run out': 'B1',
  'run out of': 'B1',
  'turn out': 'B1',
  'leave out': 'B1',
  'wear out': 'B2',
  'fall out': 'B2',
  'fall out / falling out': 'B2',
  'turn on / switch on': 'A1',
  'leave on': 'A2',
  'put on': 'A1',
  'get on': 'A2',
  'jump on / to hop on': 'A2',
  'climb on / climb onto': 'A2',
  'hang on / hold on': 'A2',
  'hold on': 'A2',
  'stay on': 'B1',
  'add on': 'B1',
  'stick on': 'A2',
  'carry on': 'B1',
  'keep on': 'B1',
  'go on': 'A2',
  'log on / sign on': 'A2',
  'log on': 'A2',
  'clock on': 'B2',
  'try on': 'A2',
  'have on': 'B1',
  'agree on': 'B1',
  'catch on': 'B2',
  'get on with': 'B1',
  'let on': 'C1',
  'take on': 'B1',
  'go off': 'B1',
  'set off': 'B1',
  'set off (a metal detector/alarm)': 'B1',
  'come off': 'B2',
  'pay off': 'B1',
  'pull off': 'B2',
  'switch off / to turn off': 'A1',
  'cut off': 'B1',
  'block off': 'B2',
  'close off': 'B2',
  'fall off': 'A2',
  'take off': 'A2',
  'rip off': 'B1',
  'run off': 'B1',
  'drive off': 'B1',
  'call off': 'B1',
  'put off': 'B1',
  'wear off': 'B2',
  'cool off': 'B1',
  'drop off': 'B1',
  'give off': 'B2',
};

function enrich() {
  const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
  let matched = 0;
  for (const item of data) {
    const level = CEFR_MAP[item.phrasal_verb.toLowerCase()];
    if (level) {
      item.cefr_level = level;
      matched++;
    } else {
      delete item.cefr_level;
    }
  }
  fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), 'utf8');
  console.log(`cefr_level añadido a ${matched}/${data.length} pistas.`);
  console.log('Ejecuta ahora: node scripts/normalize_data.js');
}

enrich();
